/* ARM template generation for a designed virtual network.
   Requires ipmath.js and subnets.js */

var ARM_API_VERSION = '2023-11-01';

function generateArm(state)
{
  var vnetPrefix = inet_ntoa(state.network)+'/'+state.mask;
  var vnetName = vnetNameFromPrefix(vnetPrefix);
  var subnets = resolveSubnetNames(collectSubnets(state.root, state.network, state.mask, []));

  var template = {
    '$schema': 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#',
    contentVersion: '1.0.0.0',
    parameters: {
      vnetName: {
        type: 'string',
        defaultValue: vnetName
      },
      location: {
        type: 'string',
        defaultValue: '[resourceGroup().location]'
      }
    },
    resources: [
      {
        type: 'Microsoft.Network/virtualNetworks',
        apiVersion: ARM_API_VERSION,
        name: "[parameters('vnetName')]",
        location: "[parameters('location')]",
        properties: {
          addressSpace: {
            addressPrefixes: [vnetPrefix]
          },
          subnets: subnets.map(function (subnet) {
            return {
              name: subnet.resolvedName,
              properties: {
                addressPrefix: subnet.prefix
              }
            };
          })
        }
      }
    ],
    outputs: {
      vnetId: {
        type: 'string',
        value: "[resourceId('Microsoft.Network/virtualNetworks', parameters('vnetName'))]"
      }
    }
  };

  var header = [
    '// Azure virtual network '+vnetPrefix+' with '+subnets.length+' subnet'+(subnets.length == 1 ? '' : 's'),
    '// Generated by the Azure CIDR designer.',
    '//',
    '// How to deploy this template:',
    '//',
    '// 1. save this content as vnet.json',
    '// 2. preview the changes:',
    '//      az deployment group what-if --resource-group <resource-group> --template-file vnet.json',
    '// 3. deploy:',
    '//      az deployment group create --resource-group <resource-group> --template-file vnet.json',
    '//',
    ''
  ].join('\n');

  return header+JSON.stringify(template, null, 2)+'\n';
}
