/* Terraform (azurerm) generation for a designed virtual network.
   Requires ipmath.js and subnets.js */

/* Terraform resource names allow letters, digits, underscores and dashes, and must start with a letter or underscore */
function sanitizeTerraformIdentifier(name)
{
  var clean = name.replace(/[^A-Za-z0-9_-]/g, '_');

  return /^[A-Za-z_]/.test(clean) ? clean : '_'+clean;
}

function resolveTerraformIdentifiers(subnets)
{
  var used = {};

  return subnets.map(function (subnet) {
    var base = sanitizeTerraformIdentifier(subnet.resolvedName);
    var identifier = base;
    var suffix = 2;

    while (used[identifier]) {
      identifier = base+'_'+suffix;
      suffix++;
    }
    used[identifier] = true;

    return identifier;
  });
}

function generateTerraform(state)
{
  var vnetPrefix = inet_ntoa(state.network)+'/'+state.mask;
  var vnetName = vnetNameFromPrefix(vnetPrefix);
  var subnets = resolveSubnetNames(collectSubnets(state.root, state.network, state.mask, []));
  var identifiers = resolveTerraformIdentifiers(subnets);

  var lines = [];

  lines.push('# Azure virtual network '+vnetPrefix+' with '+subnets.length+' subnet'+(subnets.length == 1 ? '' : 's'));
  lines.push('# Generated by the Azure CIDR designer.');
  lines.push('#');
  lines.push('# How to deploy this template:');
  lines.push('#');
  lines.push('# 1. save this content as vnet.tf');
  lines.push('# 2. initialize terraform:');
  lines.push('#      terraform init');
  lines.push('# 3. preview the changes:');
  lines.push('#      terraform plan -var "resource_group_name=<resource-group>"');
  lines.push('# 4. deploy:');
  lines.push('#      terraform apply -var "resource_group_name=<resource-group>"');
  lines.push('');
  lines.push('terraform {');
  lines.push('  required_providers {');
  lines.push('    azurerm = {');
  lines.push('      source  = "hashicorp/azurerm"');
  lines.push('      version = "~> 3.0"');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('provider "azurerm" {');
  lines.push('  features {}');
  lines.push('}');
  lines.push('');
  lines.push('variable "resource_group_name" {');
  lines.push('  type        = string');
  lines.push('  description = "Name of the existing resource group to deploy into."');
  lines.push('}');
  lines.push('');
  lines.push('variable "vnet_name" {');
  lines.push('  type    = string');
  lines.push('  default = "'+vnetName+'"');
  lines.push('}');
  lines.push('');
  lines.push('data "azurerm_resource_group" "this" {');
  lines.push('  name = var.resource_group_name');
  lines.push('}');
  lines.push('');
  lines.push('resource "azurerm_virtual_network" "vnet" {');
  lines.push('  name                = var.vnet_name');
  lines.push('  location            = data.azurerm_resource_group.this.location');
  lines.push('  resource_group_name = data.azurerm_resource_group.this.name');
  lines.push('  address_space       = ["'+vnetPrefix+'"]');
  lines.push('}');

  subnets.forEach(function (subnet, index) {
    lines.push('');
    lines.push('resource "azurerm_subnet" "'+identifiers[index]+'" {');
    lines.push('  name                 = "'+subnet.resolvedName+'"');
    lines.push('  resource_group_name  = data.azurerm_resource_group.this.name');
    lines.push('  virtual_network_name = azurerm_virtual_network.vnet.name');
    lines.push('  address_prefixes     = ["'+subnet.prefix+'"]');
    lines.push('}');
  });

  lines.push('');
  lines.push('output "vnet_id" {');
  lines.push('  value = azurerm_virtual_network.vnet.id');
  lines.push('}');
  lines.push('');
  lines.push('output "subnet_ids" {');
  lines.push('  value = {');

  subnets.forEach(function (subnet, index) {
    lines.push('    "'+subnet.resolvedName+'" = azurerm_subnet.'+identifiers[index]+'.id');
  });

  lines.push('  }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
