/* Bicep template generation for a designed virtual network.
   Requires ipmath.js and subnets.js */

var BICEP_API_VERSION = '2023-11-01';

function generateBicep(state)
{
  var vnetPrefix = inet_ntoa(state.network)+'/'+state.mask;
  var vnetName = vnetNameFromPrefix(vnetPrefix);
  var subnets = resolveSubnetNames(collectSubnets(state.root, state.network, state.mask, []));

  var lines = [];

  lines.push('/*');
  lines.push('  Azure virtual network '+vnetPrefix+' with '+subnets.length+' subnet'+(subnets.length == 1 ? '' : 's'));
  lines.push('  Generated by the Azure CIDR designer.');
  lines.push('');
  lines.push('  How to deploy this template:');
  lines.push('');
  lines.push('  1. save this content as vnet.bicep');
  lines.push('  2. preview the changes:');
  lines.push('       az deployment group what-if --resource-group <resource-group> --template-file vnet.bicep');
  lines.push('  3. deploy:');
  lines.push('       az deployment group create --resource-group <resource-group> --template-file vnet.bicep');
  lines.push('');
  lines.push('*/');
  lines.push('');
  lines.push('param location string = resourceGroup().location');
  lines.push('');
  lines.push("param vnetName string = '"+vnetName+"'");
  lines.push('');
  lines.push("resource vnet 'Microsoft.Network/virtualNetworks@"+BICEP_API_VERSION+"' = {");
  lines.push('  name: vnetName');
  lines.push('  location: location');
  lines.push('  properties: {');
  lines.push('    addressSpace: {');
  lines.push('      addressPrefixes: [');
  lines.push("        '"+vnetPrefix+"'");
  lines.push('      ]');
  lines.push('    }');
  lines.push('    subnets: [');

  subnets.forEach(function (subnet) {
    lines.push('      {');
    lines.push("        name: '"+subnet.resolvedName+"'");
    lines.push('        properties: {');
    lines.push("          addressPrefix: '"+subnet.prefix+"'");
    lines.push('        }');
    lines.push('      }');
  });

  lines.push('    ]');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('output vnetId string = vnet.id');
  lines.push('output subnetIds array = [for subnet in vnet.properties.subnets: subnet.id]');
  lines.push('');

  return lines.join('\n');
}
