/* Bicep template generation for a designed virtual network.
   Requires ipmath.js */

var BICEP_API_VERSION = '2023-11-01';

function collectSubnets(node, address, mask, out)
{
  if (node[2]) {
    collectSubnets(node[2][0], address, mask+1, out);
    collectSubnets(node[2][1], address+subnet_addresses(mask+1), mask+1, out);
  }
  else {
    out.push({
      prefix: inet_ntoa(address)+'/'+mask,
      name: (node[3] ? node[3] : '')
    });
  }
  return out;
}

function defaultSubnetName(prefix)
{
  return 'subnet-'+prefix.replace(/[.\/]/g, '-');
}

/* Azure allows letters, digits, '.', '-' and '_', and requires it to start with an alphanumeric and end with an alphanumeric or '_' */
function sanitizeSubnetName(name, prefix)
{
  var clean = name.trim().replace(/[^A-Za-z0-9._-]/g, '-').replace(/[^A-Za-z0-9_]+$/, '');

  if (clean === '') {
    return defaultSubnetName(prefix);
  }

  return /^[A-Za-z0-9]/.test(clean) ? clean : 'subnet-'+clean;
}

function resolveSubnetNames(subnets)
{
  var used = {};

  subnets.forEach(function (subnet) {
    var base = subnet.name ? sanitizeSubnetName(subnet.name, subnet.prefix) : defaultSubnetName(subnet.prefix);
    var name = base;
    var suffix = 2;

    while (used[name]) {
      name = base+'-'+suffix;
      suffix++;
    }
    used[name] = true;

    subnet.resolvedName = name;
  });

  return subnets;
}

function generateBicep(state)
{
  var vnetPrefix = inet_ntoa(state.network)+'/'+state.mask;
  var vnetName = 'vnet-'+vnetPrefix.replace(/[.\/]/g, '-');
  var subnets = resolveSubnetNames(collectSubnets(state.root, state.network, state.mask, []));

  var lines = [];

  lines.push('/*');
  lines.push('  Azure virtual network '+vnetPrefix+' with '+subnets.length+' subnet'+(subnets.length == 1 ? '' : 's'));
  lines.push('  Generated by the Azure CIDR designer.');
  lines.push('');
  lines.push('  How to deploy this template:');
  lines.push('');
  lines.push('  1. save this content as vnet.bicep');
  lines.push('  2. sign in and select the target subscription:');
  lines.push('       az login');
  lines.push('       az account set --subscription <subscription-id>');
  lines.push('  3. create (or reuse) the resource group:');
  lines.push('       az group create --name <resource-group> --location <location>');
  lines.push('  4. preview the changes:');
  lines.push('       az deployment group what-if --resource-group <resource-group> --template-file vnet.bicep');
  lines.push('  5. deploy:');
  lines.push('       az deployment group create --resource-group <resource-group> --template-file vnet.bicep');
  lines.push('');
  lines.push('  Override the defaults with --parameters vnetName=<name> location=<region>');
  lines.push('  Azure reserves 5 addresses in every subnet: the first 4 and the last one.');
  lines.push('*/');
  lines.push('');
  lines.push('param location string = resourceGroup().location');
  lines.push('');
  lines.push("param vnetName string = '"+vnetName+"'");
  lines.push('');
  lines.push("resource vnet 'Microsoft.Network/virtualNetworks@"+BICEP_API_VERSION+"' = {");
  lines.push('  name: vnetName');
  lines.push('  location: location');
  lines.push('  properties: {');
  lines.push('    addressSpace: {');
  lines.push('      addressPrefixes: [');
  lines.push("        '"+vnetPrefix+"'");
  lines.push('      ]');
  lines.push('    }');
  lines.push('    subnets: [');

  subnets.forEach(function (subnet) {
    lines.push('      {');
    lines.push("        name: '"+subnet.resolvedName+"'");
    lines.push('        properties: {');
    lines.push("          addressPrefix: '"+subnet.prefix+"'");
    lines.push('        }');
    lines.push('      }');
  });

  lines.push('    ]');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('output vnetId string = vnet.id');
  lines.push('output subnetIds array = [for subnet in vnet.properties.subnets: subnet.id]');
  lines.push('');

  return lines.join('\n');
}
